Testing
Naledi-Dikgale/math-magician-project pull request #6
Opened 2023-05-03 11:05 UTC by Naledi-Dikgale

**In this Pull Request we did the following**

- Set up React Testing Library.
- Wrote unit tests for the files operate.js and calculate.js using Jest.
- Created unit tests for all React components:
- Used Jest snapshots to test the components.
- Used React Testing Library to simulate user interaction.
- Ran full tests suite using Jest and ensured that all tests pass.

2023-05-03 13:03 UTC, julie-ify requested changes
## Hi @Naledi-Dikgale and @boniface193,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 13:03 UTC, julie-ify commented on src/test.js/operate.test.js
> +});
- [ ] Kindly add more tests covering all operation signs in the logic file.

2023-05-03 13:03 UTC, julie-ify commented on src/test.js/calculate.test.js
> +});
- [ ] Kindly write more tests covering more scenarios.

2023-05-03 13:03 UTC, julie-ify commented on README.md
- [ ] You have added tests for only the logic files. Kindly add snapshot tests for all your components namely Calculator, Display, Home, Navigation, and Quote.

- [ ] Kindly add tests using the react testing library to simulate user interactions. You can see this tutorial: https://www.robinwieruch.de/react-testing-library/.

2023-05-04 12:27 UTC, Abenezer-Tilahun commented on src/test.js/operate.test.js
> +});
Fixed.

2023-05-04 12:28 UTC, Abenezer-Tilahun commented on src/test.js/calculate.test.js
> +});
Fixed.

2023-05-04 12:29 UTC, Abenezer-Tilahun approved these changes
Hi @Naledi-Dikgale 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git -Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.


## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 13:03 UTC, merged